[package]
name = "xtask"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
rustix.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2.workspace = true

[lints]
workspace = true
